name: Trimming Group 2

on:
  push:
    branches:
      - main
      - docker-test
      - trimming-g2
    # ⬇️ THE MAGIC TRICK: This action ONLY triggers if files in this folder change!
    paths:
      - 'containers/trimming_g2/**' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # ⬇️ Tells Docker to look inside Group 2's folder for the Dockerfile
          context: ./containers/trimming_g2
          push: true
          tags: hcemm/bioinfo-workshop:trimming #one repo with different tags (or seperate repos...)